name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run Build Script (Paver with tests)
        run: ./build.sh
